services:
  - type: web
    name: emotional-companion-api
    env: node
    rootDirectory: src
    buildCommand: cd src && npm install
    startCommand: cd src && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: FRONTEND_DOMAIN
        value: https://ivory-wombat-811991.hostingersite.com/
